
package ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.netbeans.xml.schema.gestion.Documento;
import org.netbeans.xml.schema.gestion.DocumentoPdfResponse;
import org.netbeans.xml.schema.gestion.DocumentoResponse;
import org.netbeans.xml.schema.gestion.Pedido2Response;
import org.netbeans.xml.schema.gestion.PedidoExt;
import org.netbeans.xml.schema.gestion.PedidoResponse;
import org.netbeans.xml.schema.gestion.PedidosResponse;
import org.netbeans.xml.schema.gestion.PrecioArticuloResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Gestion", targetNamespace = "http://ws/")
@XmlSeeAlso({
    org.netbeans.xml.schema.comun.ObjectFactory.class,
    org.netbeans.xml.schema.gestion.ObjectFactory.class,
    ws.ObjectFactory.class
})
public interface Gestion {


    /**
     * 
     * @param password
     * @param grupo
     * @param usuario
     * @param clienteCodigo
     * @param clienteCentro
     * @return
     *     returns org.netbeans.xml.schema.gestion.PedidosResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPedidosPendienteCliente", targetNamespace = "http://ws/", className = "ws.GetPedidosPendienteCliente")
    @ResponseWrapper(localName = "getPedidosPendienteClienteResponse", targetNamespace = "http://ws/", className = "ws.GetPedidosPendienteClienteResponse")
    @Action(input = "http://ws/Gestion/getPedidosPendienteClienteRequest", output = "http://ws/Gestion/getPedidosPendienteClienteResponse")
    public PedidosResponse getPedidosPendienteCliente(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "grupo", targetNamespace = "")
        String grupo,
        @WebParam(name = "clienteCodigo", targetNamespace = "")
        String clienteCodigo,
        @WebParam(name = "clienteCentro", targetNamespace = "")
        String clienteCentro);

    /**
     * 
     * @param password
     * @param pedido
     * @param usuario
     * @return
     *     returns org.netbeans.xml.schema.gestion.PedidoResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setPedidoWeb", targetNamespace = "http://ws/", className = "ws.SetPedidoWeb")
    @ResponseWrapper(localName = "setPedidoWebResponse", targetNamespace = "http://ws/", className = "ws.SetPedidoWebResponse")
    @Action(input = "http://ws/Gestion/setPedidoWebRequest", output = "http://ws/Gestion/setPedidoWebResponse")
    public PedidoResponse setPedidoWeb(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "pedido", targetNamespace = "")
        PedidoExt pedido);

    /**
     * 
     * @param idArticulo
     * @param password
     * @param usuario
     * @return
     *     returns org.netbeans.xml.schema.gestion.PrecioArticuloResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPrecioArticulo", targetNamespace = "http://ws/", className = "ws.GetPrecioArticulo")
    @ResponseWrapper(localName = "getPrecioArticuloResponse", targetNamespace = "http://ws/", className = "ws.GetPrecioArticuloResponse")
    @Action(input = "http://ws/Gestion/getPrecioArticuloRequest", output = "http://ws/Gestion/getPrecioArticuloResponse")
    public PrecioArticuloResponse getPrecioArticulo(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "idArticulo", targetNamespace = "")
        String idArticulo);

    /**
     * 
     * @param password
     * @param pedido
     * @param usuario
     * @return
     *     returns org.netbeans.xml.schema.gestion.PedidoResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setPedido", targetNamespace = "http://ws/", className = "ws.SetPedido")
    @ResponseWrapper(localName = "setPedidoResponse", targetNamespace = "http://ws/", className = "ws.SetPedidoResponse")
    @Action(input = "http://ws/Gestion/setPedidoRequest", output = "http://ws/Gestion/setPedidoResponse")
    public PedidoResponse setPedido(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "pedido", targetNamespace = "")
        PedidoExt pedido);

    /**
     * 
     * @param password
     * @param numero
     * @param serie
     * @param usuario
     * @return
     *     returns org.netbeans.xml.schema.gestion.Pedido2Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPedido", targetNamespace = "http://ws/", className = "ws.GetPedido")
    @ResponseWrapper(localName = "getPedidoResponse", targetNamespace = "http://ws/", className = "ws.GetPedidoResponse")
    @Action(input = "http://ws/Gestion/getPedidoRequest", output = "http://ws/Gestion/getPedidoResponse")
    public Pedido2Response getPedido(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "serie", targetNamespace = "")
        String serie,
        @WebParam(name = "numero", targetNamespace = "")
        String numero);

    /**
     * 
     * @param password
     * @param documento
     * @param usuario
     * @return
     *     returns org.netbeans.xml.schema.gestion.DocumentoResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setDocumento", targetNamespace = "http://ws/", className = "ws.SetDocumento")
    @ResponseWrapper(localName = "setDocumentoResponse", targetNamespace = "http://ws/", className = "ws.SetDocumentoResponse")
    @Action(input = "http://ws/Gestion/setDocumentoRequest", output = "http://ws/Gestion/setDocumentoResponse")
    public DocumentoResponse setDocumento(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "documento", targetNamespace = "")
        Documento documento);

    /**
     * 
     * @param tipoDocumento
     * @param password
     * @param numero
     * @param serie
     * @param usuario
     * @return
     *     returns org.netbeans.xml.schema.gestion.DocumentoResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocumento", targetNamespace = "http://ws/", className = "ws.GetDocumento")
    @ResponseWrapper(localName = "getDocumentoResponse", targetNamespace = "http://ws/", className = "ws.GetDocumentoResponse")
    @Action(input = "http://ws/Gestion/getDocumentoRequest", output = "http://ws/Gestion/getDocumentoResponse")
    public DocumentoResponse getDocumento(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "tipoDocumento", targetNamespace = "")
        String tipoDocumento,
        @WebParam(name = "serie", targetNamespace = "")
        String serie,
        @WebParam(name = "numero", targetNamespace = "")
        Long numero);

    /**
     * 
     * @param agente
     * @param password
     * @param fechaInicio
     * @param usuario
     * @param fechaFin
     * @return
     *     returns org.netbeans.xml.schema.gestion.PedidosResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPedidosAgenteFecha", targetNamespace = "http://ws/", className = "ws.GetPedidosAgenteFecha")
    @ResponseWrapper(localName = "getPedidosAgenteFechaResponse", targetNamespace = "http://ws/", className = "ws.GetPedidosAgenteFechaResponse")
    @Action(input = "http://ws/Gestion/getPedidosAgenteFechaRequest", output = "http://ws/Gestion/getPedidosAgenteFechaResponse")
    public PedidosResponse getPedidosAgenteFecha(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "agente", targetNamespace = "")
        String agente,
        @WebParam(name = "fechaInicio", targetNamespace = "")
        String fechaInicio,
        @WebParam(name = "fechaFin", targetNamespace = "")
        String fechaFin);

    /**
     * 
     * @param tipoDocumento
     * @param password
     * @param numero
     * @param serie
     * @param usuario
     * @return
     *     returns org.netbeans.xml.schema.gestion.DocumentoPdfResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocumentoPdf", targetNamespace = "http://ws/", className = "ws.GetDocumentoPdf")
    @ResponseWrapper(localName = "getDocumentoPdfResponse", targetNamespace = "http://ws/", className = "ws.GetDocumentoPdfResponse")
    @Action(input = "http://ws/Gestion/getDocumentoPdfRequest", output = "http://ws/Gestion/getDocumentoPdfResponse")
    public DocumentoPdfResponse getDocumentoPdf(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "tipoDocumento", targetNamespace = "")
        String tipoDocumento,
        @WebParam(name = "serie", targetNamespace = "")
        String serie,
        @WebParam(name = "numero", targetNamespace = "")
        Long numero);

    /**
     * 
     * @param password
     * @param pedido
     * @param usuario
     * @return
     *     returns org.netbeans.xml.schema.gestion.PedidoResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setPedidoWeb3", targetNamespace = "http://ws/", className = "ws.SetPedidoWeb3")
    @ResponseWrapper(localName = "setPedidoWeb3Response", targetNamespace = "http://ws/", className = "ws.SetPedidoWeb3Response")
    @Action(input = "http://ws/Gestion/setPedidoWeb3Request", output = "http://ws/Gestion/setPedidoWeb3Response")
    public PedidoResponse setPedidoWeb3(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "pedido", targetNamespace = "")
        PedidoExt pedido);

    /**
     * 
     * @param password
     * @param pedido
     * @param usuario
     * @return
     *     returns org.netbeans.xml.schema.gestion.PedidoResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setPedidoWeb2", targetNamespace = "http://ws/", className = "ws.SetPedidoWeb2")
    @ResponseWrapper(localName = "setPedidoWeb2Response", targetNamespace = "http://ws/", className = "ws.SetPedidoWeb2Response")
    @Action(input = "http://ws/Gestion/setPedidoWeb2Request", output = "http://ws/Gestion/setPedidoWeb2Response")
    public PedidoResponse setPedidoWeb2(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "pedido", targetNamespace = "")
        PedidoExt pedido);

}
